"""Add tables

Revision ID: f7261d2ae6e2
Revises: 697c7c882b71
Create Date: 2021-07-09 03:42:16.707266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7261d2ae6e2'
down_revision = '697c7c882b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('picture', sa.String(), nullable=True),
                    sa.Column('password', sa.String(256), nullable=True),
                    sa.Column('google_auth', sa.Boolean(), nullable=False),
                    sa.Column('hse_auth', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###

