version: '3'

services:
  api_gateway:
    build: ./app
    container_name: api_gateway
    ports:
      - '127.0.0.1:8082:8082'
    env_file:
      - ./app/.env
    command: bash -c "alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8082"
    volumes:
      - ./app/:/usr/src/gateway-app/
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env

volumes:
  postgres_data: